### ISSUE TITLE
Upgrade to embree v2.17.7

### ISSUE THREAD

**Issue by aluo-x** [conda-forge/embree-feedstock#17]
Could we update embree to v2.17.7, I believe that the only breaking change relates to UVs and quads, which I don't believe pyembree uses. 

Since it is the last release of embree v2, I think we should update to this. 

A benchmark using trimesh + pyembree + embree 2.17.7 seems to work on my local machine, and is around 50% faster (33% less time) for ray tracing the same mesh.

**Comment by aluo-x** [comment]
https://github.com/embree/embree/releases/tag/v2.17.7
Tagging @scopatz @Xarthisius

**Comment by aluo-x** [comment]
I think this is the only breaking change:
https://github.com/embree/embree/blob/master/CHANGELOG.md#new-features-in-embree-2162

Since pyembree already accounts for the change in 2.15.0:
https://github.com/embree/embree/blob/master/CHANGELOG.md#new-features-in-embree-2150

**Comment by scopatz** [comment]
PRs welcome!

**Comment by aluo-x** [comment]
@scopatz I have made the pull request. I learned that Trimesh which uses pyembree & embree has already been using embree [2.17.7 for months](https://github.com/mikedh/trimesh/blob/master/docker/builds/embree.bash). On Linux, building against 2.17.7 and running the usual ray tracing code gives me quite a speed up on an AMD Zen 2 Threadripper.

Would be nice to have this as default.

**Comment by joaander** [comment]
Fixed in #17.
