### ISSUE TITLE
embree installs all contents not just library to CONDA_PREFIX

### ISSUE THREAD

**Issue by LunarLanding** [conda-forge/embree-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have for instance in $CONDA_PREFIX/bin  a models folder.
This is because the build script just copies the entire embree repository, not just headers or appropriately named binaries.
Shouldn't it be more restrictive?

### Installed packages

```shell
NOT RELEVANT
```

### Environment info

```shell
NOT RELEVANT
```

**Comment by joaander** [comment]
Fixed in #30.
