### ISSUE TITLE
embree and tbb

### ISSUE THREAD

**Issue by oleg-alexandrov** [conda-forge/embree-feedstock#42]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The OSX conda package embree-2.17.7-h694c41f_3 comes with its own libtbb.dylib and libtbbmalloc.dylib, which conflicts with tbb-devel=2021.10.0. If I install the latter, it removes  libtbb.dylib and libtbbmalloc.dylib and replaces them with symlinks to libtbb.12.dylib and libtbbmalloc.2.dylib. But then embree cannot find some symbols it needs. 

The root of the problem, seems to me, that embree should have no business shipping its own tbb, especially with no version number, and instead should use the tbb and/or tbb-devel conda packages, with a specified version. 

In my own code I do need tbb-devel, as it has header files needed by one package, and also need embree, which is needed by another package. That results in a problem as one can't have both.

Any thoughts? Thank you. 
 

### Installed packages

```shell
embree                    2.17.7               h694c41f_3    conda-forge
tbb                       2021.10.0            h1c7c39f_0    conda-forge
tbb-devel                 2021.10.0            h1c7c39f_0    conda-forge
```

### Environment info

```shell
active environment : asp_tmp
    active env location : /Users/oalexan1/miniconda3/envs/asp_tmp
            shell level : 2
       user config file : /Users/oalexan1/.condarc
 populated config files : /Users/oalexan1/miniconda3/.condarc
                          /Users/oalexan1/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/oalexan1/miniconda3  (writable)
      conda av data dir : /Users/oalexan1/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/nasa-ames-stereo-pipeline/osx-64
                          https://conda.anaconda.org/nasa-ames-stereo-pipeline/noarch
                          https://conda.anaconda.org/usgs-astrogeology/osx-64
                          https://conda.anaconda.org/usgs-astrogeology/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/oalexan1/miniconda3/pkgs
                          /Users/oalexan1/.conda/pkgs
       envs directories : /Users/oalexan1/miniconda3/envs
                          /Users/oalexan1/.conda/envs
               platform : osx-64
             user-agent : conda/4.14.0 requests/2.31.0 CPython/3.7.3 Darwin/21.6.0 OSX/10.16
                UID:GID : 507:20
             netrc file : None
           offline mode : False
```

**Comment by oleg-alexandrov** [comment]
For the record, here is the offending embree package shipping tbb: https://conda.anaconda.org/conda-forge/osx-64/embree-2.17.7-h694c41f_3.tar.bz2

**Comment by joaander** [comment]
This issue is not present in the embree 3.x and 4.x builds where the recipe correctly uses the conda-forge provided `tbb` and `tbb-devel`:
https://github.com/conda-forge/embree-feedstock/blob/37797a712f126177c40d0bf0d51fb04985b81a40/recipe/meta.yaml#L27-L32
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=754998&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=1080

The embree 2 recipe installs upstream provided binaries which are built against and include a specific version of tbb chosen by the embree maintainers:
https://github.com/conda-forge/embree-feedstock/blob/830fc7fedbf0cd6921954be9f2dd1c53a282ac32/recipe/meta.yaml#L8-L16

Embree 2.x has not been maintained in many years. I suggest that you update to the currently supported embree 4 release.

**Comment by oleg-alexandrov** [comment]
Thank you. This is very helpful.
