### ISSUE TITLE
Embree 2.17.7 Proper Dependency Release

### ISSUE THREAD

**Issue by acpaquette** [conda-forge/embree-feedstock#44]
### Comment:

Hello,

I am sure I am missing context and at this point I am not sure if embree 2.17.7 is even supported but is there a reason that the last 2.17.7 release still has tbb as a built-in dependency? To follow that question is there a way that 2.17.7 could be released with proper dependencies?

I am running into issues where embree 2.17.7 has tbb 2021.9.0 packaged together but I have other dependencies that rely on tbb 2021.10.0. If tbb 2021.10.0 installs after embree, the tbb install from embree is clobbered with the 2021.10.0 install and I get this:

```
dyld[22803]: Symbol not found: __ZN3tbb4task13note_affinityEt
  Referenced from: <DAF60392-3DA0-3A5C-A860-2B4E84574A14> /Users/acpaquette/mambaforge/envs/isis_build_env/lib/libembree.2.dylib
  Expected in:     <BF31E64C-535A-38F6-B3D9-F6681FCAB774> /Users/acpaquette/mambaforge/envs/isis_build_env/lib/libtbb.12.10.dylib
  ```
  
I am sure there is history here and upgrading to embree 3 may be the best way forward. Any assistance or insight would be greatly appreciated.
  
 
Thank you,

Adam Paquette

**Comment by joaander** [comment]
embree 4.3.0 is the latest release. All releases >=3.0.0 of conda-forge/embree build embree from source and use conda-forge/tbb as a dependency.

The embree v2 feedstock (written by a previous maintainer) unpacks the binaries provided by upstream, which include the embedded tbb libraries. I would gladly review a PR onto the `v2` branch that rewrites the feedstock to build from source.

**Comment by acpaquette** [comment]
Cool, thank you @joaander. I spent some time last night updating to embree3, we will see if that works for us and if not I may be able to get an update for the v2 branch in a few months. I will close this issue for the time being.
