### ISSUE TITLE
Discussion: Planning an embree3 package

### ISSUE THREAD

**Issue by joaander** [conda-forge/embree-feedstock#7]
@conda-forge/embree I have been using this package as a dependency for another conda-forge package. I plan to update my library to use the new embree3 API which is not compatible with embree 2.x. Do you have any plans to update your package to embree3? If not, I am willing to develop and maintain such a package. 

Embree 3 and 2 can coexist in the same system as the library names are different and the includes are in different directories. The only potential for conflict are the examples in bin/ (which aren't really needed anyways) and the variety of files that your embree package puts in the root of the conda environment (embree-vars.* and doc/). I would avoid those conflicts by building embree3 from source instead of installing the packaged binaries.

I propose that I develop and submit a new embree3 package that can coexist with this one and maintain it separately. Let me know if you have other plans or preferences.

**Comment by scopatz** [comment]
Hi @joaander - I think having a separate embree3 would probably be the best scenario. Feel free to put in a PR to staged-recipes!

**Comment by joaander** [comment]
Excellent, I will do that.
